---

# Fix script names and usernames

# iptables base config
- hosts: all
  remote_user: nisse
  tasks:
    - name: Base iptables
      become: yes
      become_method: sudo
      script:
        cmd: /home/nisse/tmp
- hosts: VmServer
  remote_user: nisse
  tasks:
    - name: VmServer iptables
      become: yes
      become_method: sudo
      script:
        cmd: /home/nisse/scripts/iptablesVM.sh

- hosts: DbServer1
  remote_user: nisse
  tasks:
    - name: VmServer iptables
      become: yes
      become_method: sudo
      script:
        cmd: /home/nisse/scripts/iptablesDB.sh

- hosts: DbServer2
  remote_user: nisse
  tasks:
    - name: VmServer iptables
      become: yes
      become_method: sudo
      script:
        cmd: /home/nisse/scripts/iptablesDB.sh

- hosts: FileServer1
  remote_user: nisse
  tasks:
    - name: VmServer iptables
      become: yes
      become_method: sudo
      script:
        cmd: /home/nisse/scripts/iptablesFS.sh

- hosts: FileServer2
  remote_user: nisse
  tasks:
    - name: VmServer iptables
      become: yes
      become_method: sudo
      script:
        cmd: /home/nisse/scripts/iptablesFS.sh


