---

# Fix script names and usernames

# iptables base config
- hosts: VmServer
  remote_user: nisse
  tasks:
    - name: make dirs
      become: yes
      become_method: sudo
      script:
        cmd: /home/nisse/scripts/docker/nextcloud_host_mkdir.sh
  tasks:
    - name: run docker
      become: yes
      become_method: sudo
      script:
        cmd: docker-compose -p /home/nisse/scripts/docker/docker-compose.yml up -d
