---

# Fix script names and usernames

# iptables base config
- hosts: all
  remote_user: nisse
  tasks:
    - name: Base iptables
      become: yes
      become_method: sudo
      script:
        cmd: /home/nisse/tmp

- hosts: Web
  remote_user: nisse
  tasks:
    - name: Web iptables
      become: yes
      become_method: sudo
      script:
        cmd: /home/nisse/tmp

- hosts: VmServer
  remote_user: nisse
  tasks:
    - name: VmServer iptables
      become: yes
      become_method: sudo
      script:
        cmd: /home/nisse/tmp
