version: "3.7"

services:

  nextcloud:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./nextcloud:/var/www/html"
      - "./apps:/var/www/html/custom_apps"
      - "./config:/var/www/html/config"
      - "./data:/var/www/html/data"
    ports:
      - "8080:80"
    expose:
      - "80"

networks:
  nextcloud:

